// Generado una sola vez a partir de 'Lista de miembros' (reporte oficial
// exportado el 5 sept 2026, Valle Grande Ward) y del análisis de cuadrantes
// ya validado en Excel. No se vuelve a tocar a mano — ver seedDirectory.js.
export const DIRECTORY_SEED = [
  { name: "Acuña Muñoz, Carolina Stephanie", sex: "M", birthDate: "1984-09-19" },
  { name: "Acuña Muñoz, Mireya del Carmen de", sex: "M", birthDate: "1962-12-19" },
  { name: "Adana Gajardo, Isabel Margarita", sex: "M", birthDate: "1987-02-01" },
  { name: "Alegre Barrantes, Valentina De Las Rosas", sex: "M", birthDate: "2013-05-15" },
  { name: "Aracena Gajardo, Gabriel Patricio", sex: "V", birthDate: "1991-02-06" },
  { name: "Arancibia Correa, Paola Lorena", sex: "M", birthDate: "1971-04-20" },
  { name: "Arancibia Espinoza, Veronica", sex: "M", birthDate: "1987-06-21" },
  { name: "Araya Bruna, Constanza Camila", sex: "M", birthDate: "1994-10-03" },
  { name: "Arevalo Barras, Sergio Eduardo", sex: "V", birthDate: "1973-11-14" },
  { name: "Arevalo Urbina, Yessenia Belen", sex: "M", birthDate: "1990-09-04" },
  { name: "Arévalo Catalán, Stephany Sabrina", sex: "M", birthDate: "2008-08-11" },
  { name: "Atria, Paul Alex", sex: "V", birthDate: "1968-11-15" },
  { name: "Ayala Becerra, Lismar Angelica", sex: "M", birthDate: "1987-11-08" },
  { name: "Berrios Reyes, David Eduardo", sex: "V", birthDate: "1986-02-22" },
  { name: "Briones Carrasco, David Elias", sex: "V", birthDate: "1994-02-14" },
  { name: "Buratovich Caceres, Bruno Milovan", sex: "V", birthDate: "2014-11-05" },
  { name: "Buratovich Caceres, Drago Facundo", sex: "V", birthDate: "2012-05-06" },
  { name: "Buratovich Caceres, Javiera Ivanna", sex: "M", birthDate: "2005-03-08" },
  { name: "Buratovich Caceres, Pascale Alana", sex: "M", birthDate: "2008-08-21" },
  { name: "Caceres Bravo, Karen Noemi", sex: "M", birthDate: "1978-12-20" },
  { name: "Caceres, Karen D' Yan", sex: "M", birthDate: "1990-12-13" },
  { name: "Cancino Arredondo, Janina Eugenia", sex: "M", birthDate: "1973-01-26" },
  { name: "Caniumil Canto, Eimy Agustina", sex: "M", birthDate: "2013-10-01" },
  { name: "Canto Garrido, Betzabe Del Carmen", sex: "M", birthDate: "1979-02-06" },
  { name: "Cardenas Quiroz, Berta Del Carmen", sex: "M", birthDate: "1969-02-02" },
  { name: "Carquin Guerrero, Amanda Denisse", sex: "M", birthDate: "2019-05-11" },
  { name: "Carquin Ruiz, Anderson Iván", sex: "V", birthDate: "1991-11-07" },
  { name: "Carquín Guerrero, Esmeralda Aurora", sex: "M", birthDate: "2021-06-30" },
  { name: "Carrasco Lecaros, Benjamín Alejandro", sex: "V", birthDate: "2001-05-03" },
  { name: "Carreño Abarca, Isidora Belén", sex: "M", birthDate: "2013-05-21" },
  { name: "Carreño Abarca, León Baltazar", sex: "V", birthDate: "2017-03-20" },
  { name: "Carreño Ayala, Andres David", sex: "V", birthDate: "2013-12-16" },
  { name: "Carreño Ayala, Diego Fernando", sex: "V", birthDate: "1982-10-03" },
  { name: "Carreño Ayala, Juan Diego", sex: "V", birthDate: "2012-09-18" },
  { name: "Carreño Ayala, Santiago Alejandro", sex: "V", birthDate: "2015-10-15" },
  { name: "Carvajal Campo, Yoselyn Saray", sex: "M", birthDate: "2004-11-03" },
  { name: "Castillo Diaz, Lily", sex: "M", birthDate: "1988-01-22" },
  { name: "Cepeda Alarcon, Cesar Eduardo", sex: "V", birthDate: "1987-08-26" },
  { name: "Cepeda Forigua, Samuel Caleb", sex: "V", birthDate: "2023-08-05" },
  { name: "Colomba Andrea, Quintana Cortés", sex: "M", birthDate: "2011-08-08" },
  { name: "Contreras Hernandez, Andrea del Pilar", sex: "M", birthDate: "1976-08-07" },
  { name: "Contreras Riveros, Ignacio Juan", sex: "V", birthDate: "1999-01-01" },
  { name: "Cortes Saavedra, Marialan Valeska", sex: "M", birthDate: "1982-05-11" },
  { name: "Cotapos Urrutia, Ignacia Antonella", sex: "M", birthDate: "2011-02-24" },
  { name: "Crespo Arevalo, Amparo Belen", sex: "M", birthDate: "2020-05-18" },
  { name: "Crespo Arevalo, Cristian Benjamin", sex: "V", birthDate: "2024-03-01" },
  { name: "Crespo Arevalo, Maximo Eduardo", sex: "V", birthDate: "2017-11-09" },
  { name: "Crespo Rodriguez, Pablo Salvador", sex: "V", birthDate: "1990-05-09" },
  { name: "Cuenca Rodriguez, Jaime Ariel Rodrigo", sex: "V", birthDate: "1993-06-06" },
  { name: "Curaqueo Rauque, Joaquín Alonso", sex: "V", birthDate: "2011-07-18" },
  { name: "Curaqueo Rauque, Pascale Aylen", sex: "M", birthDate: "2019-05-20" },
  { name: "Curaqueo Ruiz, Luis Alejandro", sex: "V", birthDate: "1983-02-15" },
  { name: "De Carquin Guerrero Padilla, Jaqueline Lisette", sex: "M", birthDate: "1996-01-10" },
  { name: "Dominguez Vergara, Joisy Janeth", sex: "M", birthDate: "1976-11-03" },
  { name: "Donoso Salinas, Yolanda Patricia", sex: "M", birthDate: "1985-10-04" },
  { name: "Duran Arancibia, Agustin Alonso", sex: "V", birthDate: "2009-02-15" },
  { name: "Duran Arancibia, Martina Pascuala", sex: "M", birthDate: "2008-02-17" },
  { name: "Duran Huidobro, Rodrigo", sex: "V", birthDate: "1974-05-23" },
  { name: "Duran Macaya, Monica", sex: "M", birthDate: "1972-09-22" },
  { name: "Duran Macaya, Natalia", sex: "M", birthDate: "1998-04-10" },
  { name: "Duran Macaya, Samuel", sex: "V", birthDate: "2003-02-10" },
  { name: "Duran Osorio, Marcelo Alberto", sex: "V", birthDate: "1985-06-05" },
  { name: "Esparza Vargas, Martin Alejandro", sex: "V", birthDate: "2007-09-23" },
  { name: "Estaba Cedeño, Alba Celeste Maria", sex: "M", birthDate: "1992-07-09" },
  { name: "Esteban", sex: "V", birthDate: "1985-10-27" },
  { name: "Fariña Acuña, Mia Trinidad", sex: "M", birthDate: "2015-01-06" },
  { name: "Fariña Soto, Ricardo Andres", sex: "V", birthDate: "1987-02-05" },
  { name: "Ferrer Hernandez, Carla Denise", sex: "M", birthDate: "1988-10-09" },
  { name: "Forigua Monroy, Karen Rosario", sex: "M", birthDate: "1985-05-12" },
  { name: "Freire Carrasco, Jaime Adrian", sex: "V", birthDate: "1978-06-07" },
  { name: "Freire Rogel, Benjamin Andres", sex: "V", birthDate: "2015-12-28" },
  { name: "Freire Rogel, Matias Francisco", sex: "V", birthDate: "2012-11-25" },
  { name: "Fuentes Imiguala, Diego Adrían", sex: "V", birthDate: "1994-08-24" },
  { name: "Galvez Gonzalez, Andres Felipe", sex: "V", birthDate: "1992-09-14" },
  { name: "Garcia, Maria Jose", sex: "M", birthDate: "1985-08-01" },
  { name: "Garzón Herrera, Néstor Hernán", sex: "V", birthDate: "1970-03-26" },
  { name: "Gomez Victor, Teresa", sex: "M", birthDate: "1967-05-16" },
  { name: "Gonzalez Gonzalez, Bruno Alonso", sex: "V", birthDate: "2005-02-28" },
  { name: "Gonzalez Gonzalez, Fernanda Catalina", sex: "M", birthDate: "2011-12-28" },
  { name: "Gonzalez Maturana, Elizabeth Caroline", sex: "M", birthDate: "1981-03-25" },
  { name: "González Cáceres, Beatriz Alejandra", sex: "M", birthDate: "2000-05-01" },
  { name: "Guerrero Diaz, Fulton Eugenio", sex: "V", birthDate: "1981-02-19" },
  { name: "Guerrero Hernandez, Alonso Martin", sex: "V", birthDate: "2011-05-16" },
  { name: "Guerrero Hernandez, Emilia Paz", sex: "M", birthDate: "2007-10-21" },
  { name: "Guerrero Hernandez, Joaquín Ignacio", sex: "V", birthDate: "2009-07-24" },
  { name: "Guevara Garcia, Carlos", sex: "V", birthDate: "1988-05-13" },
  { name: "Guevara Robles, Mariana Itzel", sex: "M", birthDate: "2015-06-26" },
  { name: "Gálvez Martínez, Tamara Andrea", sex: "M", birthDate: "1993-09-15" },
  { name: "Henriquez Espinoza, Fabian Andres", sex: "V", birthDate: "1991-03-10" },
  { name: "Henriquez Johnson, Aramì Lucìa", sex: "M", birthDate: "2019-01-10" },
  { name: "Henríquez Johnson, Efrain Esteban", sex: "V", birthDate: "2025-04-02" },
  { name: "Henríquez Onel, Tomás Benjamín", sex: "V", birthDate: "2015-07-30" },
  { name: "Hernandez Gallardo, Pamela Alejandra", sex: "M", birthDate: "1979-05-07" },
  { name: "Herrera Pezoa, Nicolas Ignacio", sex: "V", birthDate: "1995-06-02" },
  { name: "Herrera Uribie, Gustavo Jose", sex: "V", birthDate: "1977-10-27" },
  { name: "Hidalgo Cancino, Constanza", sex: "M", birthDate: "2006-01-03" },
  { name: "Hidalgo Cancino, Felipe Ignacio", sex: "V", birthDate: "2007-11-25" },
  { name: "Inostroza Valdes, Segundo Florentino", sex: "V", birthDate: "1961-10-17" },
  { name: "Iribarra Macaya, Elizabeth", sex: "M", birthDate: "1985-09-08" },
  { name: "Iribarra Macaya, Yolanda", sex: "M", birthDate: "1965-01-03" },
  { name: "Iribarra Macaya, jennifer Natalia de Cuenca", sex: "M", birthDate: "1995-07-21" },
  { name: "Iribarra Vergara, Miguel", sex: "V", birthDate: "1963-11-25" },
  { name: "Jacob, Angerbe", sex: "V", birthDate: "2011-09-09" },
  { name: "Johnson Aedo, Camila Alejandra", sex: "M", birthDate: "1994-04-09" },
  { name: "Jorquera Soto, Francisco Javier", sex: "V", birthDate: "1988-10-20" },
  { name: "Lagos Garrido, Juan Sebastian", sex: "V", birthDate: "1988-03-03" },
  { name: "Lagos Ortiz, Belen Antonella", sex: "M", birthDate: "2013-10-08" },
  { name: "Lagos Ortiz, Delfina Renata", sex: "M", birthDate: "2017-04-12" },
  { name: "Lagos Ortiz, Lisandro Nahuel", sex: "V", birthDate: "2021-01-04" },
  { name: "Lira Garcia, Antonella Anais", sex: "M", birthDate: "2011-02-03" },
  { name: "Lira Garcia, Dianella Trinidad", sex: "M", birthDate: "2020-11-23" },
  { name: "Lopez Santander, Rodrigo", sex: "V", birthDate: "1987-01-27" },
  { name: "Loyola Bahamonde, Mauricio Andres", sex: "V", birthDate: "1999-01-15" },
  { name: "Luna Caceres, Cristobal Antonio", sex: "V", birthDate: "2016-10-14" },
  { name: "Manrique Dominguez, Ariana Isamar", sex: "M", birthDate: "2006-06-28" },
  { name: "Manrique Dominguez, Heidy Naomi", sex: "M", birthDate: "2013-07-05" },
  { name: "Mardones Nicosia, Francisco Javier", sex: "V", birthDate: "1990-07-23" },
  { name: "Mella Arias, Dante Emiliano", sex: "V", birthDate: "2013-05-09" },
  { name: "Mella Espejo, Cristopher Erick", sex: "V", birthDate: "1985-12-16" },
  { name: "Mendoza Correa, Patricio", sex: "V", birthDate: "1975-11-14" },
  { name: "Mendoza Valderas, Gustavo Hernan", sex: "V", birthDate: "2010-02-20" },
  { name: "Mendoza Valderas, Joaquin Patricio", sex: "V", birthDate: "2007-09-08" },
  { name: "Mendoza Valderas, Laura Catalina", sex: "M", birthDate: "2014-12-26" },
  { name: "Mila Lopez, Jorge Luis", sex: "V", birthDate: "1983-03-13" },
  { name: "Molina Rodríguez, Leticia Fernanda", sex: "M", birthDate: "2014-07-24" },
  { name: "Molina Rojas, Ambar pascale", sex: "M", birthDate: "2020-01-29" },
  { name: "Molina Rojas, Isidora Amanda", sex: "M", birthDate: "2016-01-28" },
  { name: "Molina Sanchez, Florencia Martina", sex: "M", birthDate: "2012-06-01" },
  { name: "Molina Troncoso, Eduardo Alexis", sex: "V", birthDate: "1982-08-20" },
  { name: "Nogues Contador, Israel Vicente Antonio", sex: "V", birthDate: "1995-08-29" },
  { name: "Nogues Monckeberg, Gustavo Alberto", sex: "V", birthDate: "1953-12-24" },
  { name: "Olavarria Manzanares, Laura Elizabeth", sex: "M", birthDate: "1961-03-28" },
  { name: "Olavarria Manzanares, Ruth", sex: "M", birthDate: "1957-03-19" },
  { name: "Olavarria Manzanares, Teresa Jeanette", sex: "M", birthDate: "1966-05-13" },
  { name: "Ordoñez Cortes, Barbara Andrea", sex: "M", birthDate: "1993-12-29" },
  { name: "Ortega Crisostomo, Santino", sex: "V", birthDate: "2014-12-26" },
  { name: "Ortiz Medina, Alexa Daniela", sex: "M", birthDate: "2020-01-14" },
  { name: "Ortiz Medina, Alicia Victoria", sex: "M", birthDate: "2014-01-25" },
  { name: "Ortiz Medina, Maryelim Carolina de", sex: "M", birthDate: "1986-11-17" },
  { name: "Ortiz Ortiz, Danny Bautista", sex: "V", birthDate: "1988-11-16" },
  { name: "Ortiz, Sara Jessica", sex: "M", birthDate: "1986-03-15" },
  { name: "Parada Ordoñez, Carlos Mateo Hijo", sex: "V", birthDate: "2017-12-16" },
  { name: "Perez Donoso, Rafaela Leonor", sex: "M", birthDate: "2016-07-26" },
  { name: "Perez Lara, Luis Alberto", sex: "V", birthDate: "1982-08-31" },
  { name: "Pino Rodriguez, Carlos Felipe Alberto", sex: "V", birthDate: "1996-03-07" },
  { name: "Pino Veloso, Emma Ignacia", sex: "M", birthDate: "2017-11-29" },
  { name: "Pino Veloso, Joaquin Alfonso Hijo", sex: "V", birthDate: "2021-01-03" },
  { name: "Plaza Aravena, Josefa Renata", sex: "M", birthDate: "2018-09-02" },
  { name: "Puerta Ayala, Naila Rosana", sex: "M", birthDate: "1980-10-12" },
  { name: "Puerta Ayala, Naileth Agelina", sex: "M", birthDate: "2013-07-03" },
  { name: "Puerta Peroza, Anyerbe Jose", sex: "V", birthDate: "1986-05-23" },
  { name: "Pérez Rivas, Gabriangeli Paola", sex: "M", birthDate: "2006-11-16" },
  { name: "Quintana Cortes, Alan Andres Abinadi", sex: "V", birthDate: "2005-11-03" },
  { name: "Quintana Cortes, Isidora Catalina", sex: "M", birthDate: "2009-01-18" },
  { name: "Ramirez Calderon, Fanny de Lourdes", sex: "M", birthDate: "1982-10-04" },
  { name: "Rauque Nuñez, Lidia de Lourdes", sex: "M", birthDate: "1981-11-18" },
  { name: "Reyes Ruiz, Servando Anibal", sex: "V", birthDate: "1985-07-10" },
  { name: "Riquelme Romero, Román Esteban", sex: "V", birthDate: "2010-04-06" },
  { name: "Rivero Aguilera, Tamara Andrea", sex: "M", birthDate: "1991-10-27" },
  { name: "Riveros Hernández, Damarys Jeannette", sex: "M", birthDate: "1995-09-10" },
  { name: "Rodriguez Cisternas, Clemente", sex: "V", birthDate: "2025-10-14" },
  { name: "Rodriguez Cisternas, Javiera Ignacia de", sex: "M", birthDate: "1997-09-12" },
  { name: "Rodriguez Dote, Sebastian Andres", sex: "V", birthDate: "1997-09-26" },
  { name: "Rogel Martinez, Romina Andrea", sex: "M", birthDate: "1987-01-03" },
  { name: "Rojas Gonzalez, Yasmin Yudith", sex: "M", birthDate: "1988-09-03" },
  { name: "Salinas Alvarez, Andres Ignacio", sex: "V", birthDate: "1982-11-04" },
  { name: "Salinas Ramirez, Sofia Belen", sex: "M", birthDate: "2011-12-31" },
  { name: "Salinas Ramirez, Valentina Antonella", sex: "M", birthDate: "2005-05-13" },
  { name: "Sandoval Olavarria, Agustin Eduardo", sex: "V", birthDate: "2005-03-09" },
  { name: "Silva Rojas, Cristobal Aaron", sex: "V", birthDate: "2007-03-22" },
  { name: "Solar Gutierrez, Katiuzka", sex: "M", birthDate: "1987-05-16" },
  { name: "Torres Toro, Renato Tomas", sex: "V", birthDate: "2005-10-31" },
  { name: "Umaña Iribarra, Antonella Ekatherina", sex: "M", birthDate: "2013-11-04" },
  { name: "Umaña Iribarra, Dominique Isadora", sex: "M", birthDate: "2019-07-11" },
  { name: "Valderama Ponce, Lorenzo Alonso", sex: "V", birthDate: "2003-01-22" },
  { name: "Valderas Mella, Paula Andrea", sex: "M", birthDate: "1983-06-11" },
  { name: "Valenzuela Ulloa, Felipe Andrés", sex: "V", birthDate: "1991-09-14" },
  { name: "Vargas Botia, Sandra Mercedes", sex: "M", birthDate: "1975-09-24" },
  { name: "Veloso Avila, Paloma Ignacia", sex: "M", birthDate: "1995-06-28" },
  { name: "Vergara Castro, Gissella", sex: "M", birthDate: "1997-09-19" },
  { name: "Yañez Ferrer, Agustina Isidora", sex: "M", birthDate: "2009-05-01" },
  { name: "Yañez Ferrer, Luciana Trinidad", sex: "M", birthDate: "2016-01-12" },
  { name: "Yañez Landero, Alvaro Felipe", sex: "V", birthDate: "1988-09-04" },
  { name: "de Aracena González, Maria José", sex: "M", birthDate: "1990-08-07" },
  { name: "perez Donoso, Reimundo Tomas Hijo", sex: "V", birthDate: "2019-05-11" },
];

// Enfoque Pastoral inicial: los 43 hombres adultos del análisis de Excel que
// se pudieron identificar sin ambigüedad en el directorio oficial (por nombre
// y apellido). Los otros 7 del Excel (Luis Cali, Felipe Galvez, Sebastian
// Lagos, Esteban Lazo, Christopher Mella, Alexis Molina, Felipe Pino) no se
// pudieron enlazar con certeza — hay que revisarlos a mano en la app.
export const PASTORAL_FOCUS_SEED = [
  { memberName: "Aracena Gajardo, Gabriel Patricio", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: false },
  { memberName: "Arevalo Barras, Sergio Eduardo", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Berrios Reyes, David Eduardo", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Briones Carrasco, David Elias", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Carquin Ruiz, Anderson Iván", asistencia: "Alto", tieneLlamamiento: false, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Carrasco Lecaros, Benjamín Alejandro", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Carreño Ayala, Diego Fernando", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Cepeda Alarcon, Cesar Eduardo", asistencia: "Medio", tieneLlamamiento: false, faltaConvenio: false, recomendacionVigente: false },
  { memberName: "Contreras Riveros, Ignacio Juan", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Crespo Rodriguez, Pablo Salvador", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: false },
  { memberName: "Cuenca Rodriguez, Jaime Ariel Rodrigo", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: true },
  { memberName: "Curaqueo Ruiz, Luis Alejandro", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: false },
  { memberName: "Duran Huidobro, Rodrigo", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Duran Macaya, Samuel", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Fariña Soto, Ricardo Andres", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Freire Carrasco, Jaime Adrian", asistencia: "Medio", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Fuentes Imiguala, Diego Adrían", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Garzón Herrera, Néstor Hernán", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Gonzalez Gonzalez, Bruno Alonso", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Guerrero Diaz, Fulton Eugenio", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: false },
  { memberName: "Guevara Garcia, Carlos", asistencia: "Medio", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: true },
  { memberName: "Henriquez Espinoza, Fabian Andres", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: false },
  { memberName: "Herrera Pezoa, Nicolas Ignacio", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Herrera Uribie, Gustavo Jose", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Inostroza Valdes, Segundo Florentino", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Iribarra Vergara, Miguel", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: false, recomendacionVigente: false },
  { memberName: "Jorquera Soto, Francisco Javier", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: true },
  { memberName: "Loyola Bahamonde, Mauricio Andres", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Mendoza Correa, Patricio", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: false, recomendacionVigente: false },
  { memberName: "Mila Lopez, Jorge Luis", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Nogues Contador, Israel Vicente Antonio", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Nogues Monckeberg, Gustavo Alberto", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Ortiz Ortiz, Danny Bautista", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Perez Lara, Luis Alberto", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Puerta Peroza, Anyerbe Jose", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Quintana Cortes, Alan Andres Abinadi", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: true },
  { memberName: "Reyes Ruiz, Servando Anibal", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Salinas Alvarez, Andres Ignacio", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Sandoval Olavarria, Agustin Eduardo", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: true },
  { memberName: "Silva Rojas, Cristobal Aaron", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: true },
  { memberName: "Torres Toro, Renato Tomas", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Yañez Landero, Alvaro Felipe", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Valenzuela Ulloa, Felipe Andrés", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  // Los siguientes 6 quedaron sin vincular en la primera carga (el nombre
  // corto del Excel no alcanzaba para identificarlos sin ambigüedad en el
  // directorio oficial) — el Obispado confirmó el nombre completo de cada
  // uno, ya verificado contra DIRECTORY_SEED de arriba. Un séptimo nombre
  // del Excel, "Luis Cali", ya no pertenece al barrio y por eso no se migra.
  { memberName: "Galvez Gonzalez, Andres Felipe", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Lagos Garrido, Juan Sebastian", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Esteban", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Mella Espejo, Cristopher Erick", asistencia: "Bajo", tieneLlamamiento: false, faltaConvenio: true, recomendacionVigente: false },
  { memberName: "Molina Troncoso, Eduardo Alexis", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
  { memberName: "Pino Rodriguez, Carlos Felipe Alberto", asistencia: "Alto", tieneLlamamiento: true, faltaConvenio: false, recomendacionVigente: true },
];
